# Importação dos Dados

In [1]:
import pandas as pd
df = pd.read_csv("data05.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data05.csv'

# Tratamento dos dados

In [ ]:
df.shape

(9357, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           9357 non-null   object 
 1   Time           9357 non-null   object 
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   int64  
 4   NMHC(GT)       9353 non-null   float64
 5   C6H6(GT)       9354 non-null   float64
 6   PT08.S2(NMHC)  9356 non-null   float64
 7   NOx(GT)        9355 non-null   float64
 8   PT08.S3(NOx)   9355 non-null   float64
 9   NO2(GT)        9354 non-null   float64
 10  PT08.S4(NO2)   9354 non-null   float64
 11  PT08.S5(O3)    9356 non-null   float64
 12  T              9356 non-null   float64
 13  RH             9354 non-null   float64
 14  AH             9352 non-null   float64
 15  classe         9357 non-null   int64  
dtypes: float64(12), int64(2), object(2)
memory usage: 1.1+ MB


In [ ]:
df.describe()

CO(GT)  PT08.S1(CO)     NMHC(GT)     C6H6(GT)  PT08.S2(NMHC)  \
count  9357.000000  9357.000000  9353.000000  9354.000000    9356.000000   
mean    -34.207524  1048.990061  -159.225382     1.863267     894.635100   
std      77.657170   329.832710   139.648174    41.386475     342.329871   
min    -200.000000  -200.000000  -200.000000  -200.000000    -200.000000   
25%       0.600000   921.000000  -200.000000     4.000000     711.000000   
50%       1.500000  1053.000000  -200.000000     7.900000     895.000000   
75%       2.600000  1221.000000  -200.000000    13.600000    1105.000000   
max      11.900000  2040.000000  1189.000000    63.700000    2214.000000   

           NOx(GT)  PT08.S3(NOx)      NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
count  9355.000000   9355.000000  9354.000000   9354.000000  9356.000000   
mean    168.607590    794.997755    58.138871   1391.466218   975.060389   
std     257.452849    322.015253   126.959066    467.262604   456.961218   
min    -200.000000   -200.000000  -200.000000   -200.000000  -200.000000   
25%      50.000000    637.000000    53.000000   1185.000000   700.000000   
50%     141.000000    794.000000    96.000000   1446.000000   942.000000   
75%     284.000000    960.000000   133.000000   1662.000000  1255.250000   
max    1479.000000   2683.000000   340.000000   2775.000000  2523.000000   

                 T           RH           AH       classe  
count  9356.000000  9354.000000  9352.000000  9357.000000  
mean      9.777533    39.481110    -6.841660     0.546650  
std      43.205868    51.223682    38.986694     0.497846  
min    -200.000000  -200.000000  -200.000000     0.000000  
25%      10.900000    34.100000     0.692250     0.000000  
50%      17.200000    48.550000     0.977300     1.000000  
75%      24.100000    61.900000     1.296650     1.000000  
max      44.600000    88.700000     2.231000     1.000000

In [ ]:
df[df.isnull().any(axis=1)]

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
64    13/03/04  10:00:00     3.2         1447       NaN      12.9   
65    13/03/04  11:00:00     4.1         1542     283.0       NaN   
67    13/03/04  13:00:00     2.8         1328     154.0      12.3   
69    13/03/04  15:00:00     2.0         1240     108.0       9.2   
71    13/03/04  17:00:00     2.3         1326      97.0      10.6   
79    14/03/04  01:00:00     2.8         1484       NaN      11.9   
82    14/03/04  04:00:00  -200.0         1130      56.0       5.2   
84    14/03/04  06:00:00     1.0         1076      29.0       2.5   
85    14/03/04  07:00:00     0.9         1028      27.0       2.4   
88    14/03/04  10:00:00     2.2         1332     129.0       8.6   
89    14/03/04  11:00:00     2.8         1445     148.0       NaN   
181   18/03/04  07:00:00     1.5         1166      78.0       7.7   
182   18/03/04  08:00:00     4.7         1643       NaN      23.3   
184   18/03/04  10:00:00     4.5         1617    -200.0      21.3   
281   22/03/04  11:00:00     1.6         1090    -200.0       7.3   
288   22/03/04  18:00:00     3.8         1407     426.0      18.3   
297   23/03/04  03:00:00     0.5          892      36.0       1.2   
299   23/03/04  05:00:00     0.3          834       NaN       0.6   
1805  24/05/04  23:00:00     0.8          853    -200.0       5.0   
1806  25/05/04  00:00:00     0.5          859    -200.0       4.3   
1809  25/05/04  03:00:00  -200.0          752    -200.0       NaN   
2989  13/07/04  07:00:00     4.0         1176    -200.0      23.8   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
64           1081.0    250.0         869.0    126.0        1667.0   
65           1184.0    296.0         808.0    158.0           NaN   
67           1059.0    153.0         987.0    124.0        1600.0   
69            947.0    119.0        1049.0      NaN        1532.0   
71           1000.0    148.0         976.0    125.0        1602.0   
79           1045.0    174.0         880.0    119.0        1624.0   
82            773.0     70.0        1130.0     82.0        1452.0   
84            618.0     44.0        1395.0     63.0           NaN   
85            615.0     74.0        1384.0      NaN        1340.0   
88            923.0    144.0           NaN     98.0        1614.0   
89           1009.0    176.0         878.0    114.0        1696.0   
181           885.0    139.0        1005.0      NaN        1551.0   
182          1384.0    339.0         667.0    124.0        2094.0   
184          1333.0      NaN         686.0    150.0        2010.0   
281           868.0    124.0        1026.0     87.0        1509.0   
288          1249.0    213.0         720.0    129.0        1932.0   
297             NaN   -200.0        1522.0   -200.0        1285.0   
299           459.0     13.0        1908.0     22.0        1212.0   
1805          762.0      NaN        1134.0     86.0        1184.0   
1806          727.0     65.0        1120.0     84.0           NaN   
1809          515.0   -200.0        1472.0   -200.0        1068.0   
2989         1398.0    339.0           NaN    111.0        2120.0   

      PT08.S5(O3)     T    RH      AH  classe  
64         1465.0  12.4   NaN  0.7335       0  
65         1583.0  15.6  42.2  0.7451       0  
67         1101.0  19.4  31.3     NaN       0  
69          947.0  18.4  33.6  0.7042       0  
71            NaN  16.7  37.8  0.7117       1  
79         1530.0  14.6  51.5  0.8536       0  
82         1051.0  12.1   NaN  0.8603       1  
84          872.0  11.6  62.2  0.8473       1  
85          853.0  10.4  67.6  0.8530       1  
88         1225.0  14.5  53.1  0.8728       0  
89         1355.0  16.9   NaN  0.8789       0  
181        1075.0  10.6  63.3  0.8067       0  
182        1610.0  11.5  60.0     NaN       0  
184        1819.0  17.8  40.5  0.8210       0  
281         766.0  18.5  36.7     NaN       1  
288        1276.0   NaN  43.1  0.8264       0  
297         456.0 

In [ ]:
df.dropna(subset = ['Date','Time','CO(GT)','PT08.S1(CO)','NMHC(GT)','C6H6(GT)','PT08.S2(NMHC)','NOx(GT)','PT08.S3(NOx)','NO2(GT)','PT08.S4(NO2)','PT08.S5(O3)','T','RH','AH','classe'], inplace=True)
df

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0     10/03/04  18:00:00     2.6         1360     150.0      11.9   
1     10/03/04  19:00:00     2.0         1292     112.0       9.4   
2     10/03/04  20:00:00     2.2         1402      88.0       9.0   
3     10/03/04  21:00:00     2.2         1376      80.0       9.2   
4     10/03/04  22:00:00     1.6         1272      51.0       6.5   
...        ...       ...     ...          ...       ...       ...   
9352  04/04/05  10:00:00     3.1         1314    -200.0      13.5   
9353  04/04/05  11:00:00     2.4         1163    -200.0      11.4   
9354  04/04/05  12:00:00     2.4         1142    -200.0      12.4   
9355  04/04/05  13:00:00     2.1         1003    -200.0       9.5   
9356  04/04/05  14:00:00     2.2         1071    -200.0      11.9   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0            1046.0    166.0        1056.0    113.0        1692.0   
1             955.0    103.0        1174.0     92.0        1559.0   
2             939.0    131.0        1140.0    114.0        1555.0   
3             948.0    172.0        1092.0    122.0        1584.0   
4             836.0    131.0        1205.0    116.0        1490.0   
...             ...      ...           ...      ...           ...   
9352         1101.0    472.0         539.0    190.0        1374.0   
9353         1027.0    353.0         604.0    179.0        1264.0   
9354         1063.0    293.0         603.0    175.0        1241.0   
9355          961.0    235.0         702.0    156.0        1041.0   
9356         1047.0    265.0         654.0    168.0        1129.0   

      PT08.S5(O3)     T    RH      AH  classe  
0          1268.0  13.6  48.9  0.7578       0  
1           972.0  13.3  47.7  0.7255       0  
2          1074.0  11.9  54.0  0.7502       0  
3          1203.0  11.0  60.0  0.7867       0  
4          1110.0  11.2  59.6  0.7888       0  
...           ...   ...   ...     ...     ...  
9352       1729.0  21.9  29.3  0.7568       0  
9353       1269.0  24.3  23.7  0.7119       0  
9354       1092.0  26.9  18.3  0.6406       0  
9355        770.0  28.3  13.5  0.5139       1  
9356        816.0  28.5  13.1  0.5028       1  

[9335 rows x 16 columns]

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH, classe]
Index: []

In [ ]:
df.isna().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
classe           0
dtype: int64

In [ ]:
df = df.reset_index (drop=True)
df

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0     10/03/04  18:00:00     2.6         1360     150.0      11.9   
1     10/03/04  19:00:00     2.0         1292     112.0       9.4   
2     10/03/04  20:00:00     2.2         1402      88.0       9.0   
3     10/03/04  21:00:00     2.2         1376      80.0       9.2   
4     10/03/04  22:00:00     1.6         1272      51.0       6.5   
...        ...       ...     ...          ...       ...       ...   
9330  04/04/05  10:00:00     3.1         1314    -200.0      13.5   
9331  04/04/05  11:00:00     2.4         1163    -200.0      11.4   
9332  04/04/05  12:00:00     2.4         1142    -200.0      12.4   
9333  04/04/05  13:00:00     2.1         1003    -200.0       9.5   
9334  04/04/05  14:00:00     2.2         1071    -200.0      11.9   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0            1046.0    166.0        1056.0    113.0        1692.0   
1             955.0    103.0        1174.0     92.0        1559.0   
2             939.0    131.0        1140.0    114.0        1555.0   
3             948.0    172.0        1092.0    122.0        1584.0   
4             836.0    131.0        1205.0    116.0        1490.0   
...             ...      ...           ...      ...           ...   
9330         1101.0    472.0         539.0    190.0        1374.0   
9331         1027.0    353.0         604.0    179.0        1264.0   
9332         1063.0    293.0         603.0    175.0        1241.0   
9333          961.0    235.0         702.0    156.0        1041.0   
9334         1047.0    265.0         654.0    168.0        1129.0   

      PT08.S5(O3)     T    RH      AH  classe  
0          1268.0  13.6  48.9  0.7578       0  
1           972.0  13.3  47.7  0.7255       0  
2          1074.0  11.9  54.0  0.7502       0  
3          1203.0  11.0  60.0  0.7867       0  
4          1110.0  11.2  59.6  0.7888       0  
...           ...   ...   ...     ...     ...  
9330       1729.0  21.9  29.3  0.7568       0  
9331       1269.0  24.3  23.7  0.7119       0  
9332       1092.0  26.9  18.3  0.6406       0  
9333        770.0  28.3  13.5  0.5139       1  
9334        816.0  28.5  13.1  0.5028       1  

[9335 rows x 16 columns]

In [ ]:
df.columns = ['Data','Hora','Cobalto', 'OxidoEstanho','HidrocarbonetosNãoMetanicos', 'Benzeno','Titania','ConcentraçãoNOx','OxidoTungstênioNOx','ConcentraçãoNO2','OxidoTungstênioNO2','OxidoÍndioO3','Temperatura-C°','UmidadeRelativa (%)','UmidadeAbsoluta','Classe']
df

Data      Hora  Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  \
0     10/03/04  18:00:00      2.6          1360                        150.0   
1     10/03/04  19:00:00      2.0          1292                        112.0   
2     10/03/04  20:00:00      2.2          1402                         88.0   
3     10/03/04  21:00:00      2.2          1376                         80.0   
4     10/03/04  22:00:00      1.6          1272                         51.0   
...        ...       ...      ...           ...                          ...   
9330  04/04/05  10:00:00      3.1          1314                       -200.0   
9331  04/04/05  11:00:00      2.4          1163                       -200.0   
9332  04/04/05  12:00:00      2.4          1142                       -200.0   
9333  04/04/05  13:00:00      2.1          1003                       -200.0   
9334  04/04/05  14:00:00      2.2          1071                       -200.0   

      Benzeno  Titania  ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0        11.9   1046.0            166.0              1056.0            113.0   
1         9.4    955.0            103.0              1174.0             92.0   
2         9.0    939.0            131.0              1140.0            114.0   
3         9.2    948.0            172.0              1092.0            122.0   
4         6.5    836.0            131.0              1205.0            116.0   
...       ...      ...              ...                 ...              ...   
9330     13.5   1101.0            472.0               539.0            190.0   
9331     11.4   1027.0            353.0               604.0            179.0   
9332     12.4   1063.0            293.0               603.0            175.0   
9333      9.5    961.0            235.0               702.0            156.0   
9334     11.9   1047.0            265.0               654.0            168.0   

      OxidoTungstênioNO2  OxidoÍndioO3  Temperatura-C°  UmidadeRelativa (%)  \
0                 1692.0        1268.0            13.6                 48.9   
1                 1559.0         972.0            13.3                 47.7   
2                 1555.0        1074.0            11.9                 54.0   
3                 1584.0        1203.0            11.0                 60.0   
4                 1490.0        1110.0            11.2                 59.6   
...                  ...           ...             ...                  ...   
9330              1374.0        1729.0            21.9                 29.3   
9331              1264.0        1269.0            24.3                 23.7   
9332              1241.0        1092.0            26.9                 18.3   
9333              1041.0         770.0            28.3                 13.5   
9334              1129.0         816.0            28.5                 13.1   

      UmidadeAbsoluta  Classe  
0              0.7578       0  
1              0.7255       0  
2              0.7502       0  
3              0.7867       0  
4              0.7888       0  
...               ...     ...  
9330           0.7568       0  
9331           0.7119       0  
9332           0.6406       0  
9333           0.5139       1  
9334           0.5028       1  

[9335 rows x 16 columns]

In [ ]:
df_2=df

In [ ]:
df_2 = df.drop(columns=['Data','Hora'])
df_2.head()

Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0      2.6          1360                        150.0     11.9   1046.0   
1      2.0          1292                        112.0      9.4    955.0   
2      2.2          1402                         88.0      9.0    939.0   
3      2.2          1376                         80.0      9.2    948.0   
4      1.6          1272                         51.0      6.5    836.0   

   ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  OxidoTungstênioNO2  \
0            166.0              1056.0            113.0              1692.0   
1            103.0              1174.0             92.0              1559.0   
2            131.0              1140.0            114.0              1555.0   
3            172.0              1092.0            122.0              1584.0   
4            131.0              1205.0            116.0              1490.0   

   OxidoÍndioO3  Temperatura-C°  UmidadeRelativa (%)  UmidadeAbsoluta  Classe  
0        1268.0            13.6                 48.9           0.7578       0  
1         972.0            13.3                 47.7           0.7255       0  
2        1074.0            11.9                 54.0           0.7502       0  
3        1203.0            11.0                 60.0           0.7867       0  
4        1110.0            11.2                 59.6           0.7888       0

In [ ]:
df_2.replace([-200], 0, inplace=True)

In [ ]:
df_2

Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0         2.6          1360                        150.0     11.9   1046.0   
1         2.0          1292                        112.0      9.4    955.0   
2         2.2          1402                         88.0      9.0    939.0   
3         2.2          1376                         80.0      9.2    948.0   
4         1.6          1272                         51.0      6.5    836.0   
...       ...           ...                          ...      ...      ...   
9330      3.1          1314                          0.0     13.5   1101.0   
9331      2.4          1163                          0.0     11.4   1027.0   
9332      2.4          1142                          0.0     12.4   1063.0   
9333      2.1          1003                          0.0      9.5    961.0   
9334      2.2          1071                          0.0     11.9   1047.0   

      ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0               166.0              1056.0            113.0   
1               103.0              1174.0             92.0   
2               131.0              1140.0            114.0   
3               172.0              1092.0            122.0   
4               131.0              1205.0            116.0   
...               ...                 ...              ...   
9330            472.0               539.0            190.0   
9331            353.0               604.0            179.0   
9332            293.0               603.0            175.0   
9333            235.0               702.0            156.0   
9334            265.0               654.0            168.0   

      OxidoTungstênioNO2  OxidoÍndioO3  Temperatura-C°  UmidadeRelativa (%)  \
0                 1692.0        1268.0            13.6                 48.9   
1                 1559.0         972.0            13.3                 47.7   
2                 1555.0        1074.0            11.9                 54.0   
3                 1584.0        1203.0            11.0                 60.0   
4                 1490.0        1110.0            11.2                 59.6   
...                  ...           ...             ...                  ...   
9330              1374.0        1729.0            21.9                 29.3   
9331              1264.0        1269.0            24.3                 23.7   
9332              1241.0        1092.0            26.9                 18.3   
9333              1041.0         770.0            28.3                 13.5   
9334              1129.0         816.0            28.5                 13.1   

      UmidadeAbsoluta  Classe  
0              0.7578       0  
1              0.7255       0  
2              0.7502       0  
3              0.7867       0  
4              0.7888       0  
...               ...     ...  
9330           0.7568       0  
9331           0.7119       0  
9332           0.6406       0  
9333           0.5139       1  
9334           0.5028       1  

[9335 rows x 14 columns]

# Teste

In [ ]:
df_2.shape

(9335, 14)

In [ ]:
feature_columns = ['Cobalto', 'OxidoEstanho','HidrocarbonetosNãoMetanicos','Benzeno','Titania','ConcentraçãoNOx','OxidoTungstênioNOx','ConcentraçãoNO2','OxidoTungstênioNO2','OxidoÍndioO3']
x = df_2[feature_columns].values
y = df_2['Classe'].values
y

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=2)

In [ ]:
print(x_train.shape)
print(x_test.shape)

(7468, 10)
(1867, 10)


In [ ]:
print(y_train.shape)
print(y_test.shape)

(7468,)
(1867,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier (n_neighbors=3)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)*100
print ('Acuracia: ', str(round(accuracy,2))+ "%")

Acuracia:  98.61%


In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred) 
cm

array([[ 814,   13],
       [  13, 1027]], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score 
print (pd.crosstab(y_test,y_pred, rownames=['Real'], colnames=['Predito'], margins=True))

Predito    0     1   All
Real                    
0        814    13   827
1         13  1027  1040
All      827  1040  1867


In [ ]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred)
print("Precision: " + str(round(precision,2)))

Precision: 0.99


In [ ]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred)
print("Recall: " + str(round(recall,2)))


Recall: 0.99


In [ ]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)
print("f1: " + str(round(f1,2)))

f1: 0.99


# Novo Tratamento

In [ ]:
df_3 = df

In [ ]:
df_3.shape

(9335, 16)

In [ ]:
df_3 = df_3.drop(columns=['Data','Hora','Temperatura-C°','UmidadeRelativa (%)','UmidadeAbsoluta'])
df_3.head()

Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0      2.6          1360                        150.0     11.9   1046.0   
1      2.0          1292                        112.0      9.4    955.0   
2      2.2          1402                         88.0      9.0    939.0   
3      2.2          1376                         80.0      9.2    948.0   
4      1.6          1272                         51.0      6.5    836.0   

   ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  OxidoTungstênioNO2  \
0            166.0              1056.0            113.0              1692.0   
1            103.0              1174.0             92.0              1559.0   
2            131.0              1140.0            114.0              1555.0   
3            172.0              1092.0            122.0              1584.0   
4            131.0              1205.0            116.0              1490.0   

   OxidoÍndioO3  Classe  
0        1268.0       0  
1         972.0       0  
2        1074.0       0  
3        1203.0       0  
4        1110.0       0

In [ ]:
df_3Cobalto=df_3[df_3['Cobalto']>-200.0]
df_3Cobalto

Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0         2.6          1360                        150.0     11.9   1046.0   
1         2.0          1292                        112.0      9.4    955.0   
2         2.2          1402                         88.0      9.0    939.0   
3         2.2          1376                         80.0      9.2    948.0   
4         1.6          1272                         51.0      6.5    836.0   
...       ...           ...                          ...      ...      ...   
9330      3.1          1314                       -200.0     13.5   1101.0   
9331      2.4          1163                       -200.0     11.4   1027.0   
9332      2.4          1142                       -200.0     12.4   1063.0   
9333      2.1          1003                       -200.0      9.5    961.0   
9334      2.2          1071                       -200.0     11.9   1047.0   

      ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0               166.0              1056.0            113.0   
1               103.0              1174.0             92.0   
2               131.0              1140.0            114.0   
3               172.0              1092.0            122.0   
4               131.0              1205.0            116.0   
...               ...                 ...              ...   
9330            472.0               539.0            190.0   
9331            353.0               604.0            179.0   
9332            293.0               603.0            175.0   
9333            235.0               702.0            156.0   
9334            265.0               654.0            168.0   

      OxidoTungstênioNO2  OxidoÍndioO3  Classe  
0                 1692.0        1268.0       0  
1                 1559.0         972.0       0  
2                 1555.0        1074.0       0  
3                 1584.0        1203.0       0  
4                 1490.0        1110.0       0  
...                  ...           ...     ...  
9330              1374.0        1729.0       0  
9331              1264.0        1269.0       0  
9332              1241.0        1092.0       0  
9333              1041.0         770.0       1  
9334              1129.0         816.0       1  

[7654 rows x 11 columns]

In [ ]:
df_3Cobalto['Cobalto'].median()

1.8

In [ ]:
df_3['Cobalto']= df_3['Cobalto'].replace([-200],1.8)
df_3['Cobalto'].value_counts()

1.8    1866
1.0     304
1.4     279
1.6     274
1.5     272
       ... 
9.9       1
7.0       1
9.3       1
7.6       1
8.5       1
Name: Cobalto, Length: 96, dtype: int64

In [ ]:
df_3OxidoEstanho=df_3[df_3['OxidoEstanho']>-200.0]
df_3OxidoEstanho

Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0         2.6          1360                        150.0     11.9   1046.0   
1         2.0          1292                        112.0      9.4    955.0   
2         2.2          1402                         88.0      9.0    939.0   
3         2.2          1376                         80.0      9.2    948.0   
4         1.6          1272                         51.0      6.5    836.0   
...       ...           ...                          ...      ...      ...   
9330      3.1          1314                       -200.0     13.5   1101.0   
9331      2.4          1163                       -200.0     11.4   1027.0   
9332      2.4          1142                       -200.0     12.4   1063.0   
9333      2.1          1003                       -200.0      9.5    961.0   
9334      2.2          1071                       -200.0     11.9   1047.0   

      ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0               166.0              1056.0            113.0   
1               103.0              1174.0             92.0   
2               131.0              1140.0            114.0   
3               172.0              1092.0            122.0   
4               131.0              1205.0            116.0   
...               ...                 ...              ...   
9330            472.0               539.0            190.0   
9331            353.0               604.0            179.0   
9332            293.0               603.0            175.0   
9333            235.0               702.0            156.0   
9334            265.0               654.0            168.0   

      OxidoTungstênioNO2  OxidoÍndioO3  Classe  
0                 1692.0        1268.0       0  
1                 1559.0         972.0       0  
2                 1555.0        1074.0       0  
3                 1584.0        1203.0       0  
4                 1490.0        1110.0       0  
...                  ...           ...     ...  
9330              1374.0        1729.0       0  
9331              1264.0        1269.0       0  
9332              1241.0        1092.0       0  
9333              1041.0         770.0       1  
9334              1129.0         816.0       1  

[8969 rows x 11 columns]

In [ ]:
df_3OxidoEstanho['OxidoEstanho'].median()

1063.0

In [ ]:
df_3['OxidoEstanho']= df_3['OxidoEstanho'].replace([-200],1063.0)
df_3['OxidoEstanho'].value_counts()

1063.0    379
973.0      30
1100.0     28
969.0      26
988.0      26
         ... 
1696.0      1
1576.0      1
728.0       1
1715.0      1
1519.0      1
Name: OxidoEstanho, Length: 1039, dtype: int64

In [ ]:
df_3HidrocarbonetosNãoMetanicos=df_3[df_3['HidrocarbonetosNãoMetanicos']>-200.0]
df_3HidrocarbonetosNãoMetanicos

Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0         2.6        1360.0                        150.0     11.9   1046.0   
1         2.0        1292.0                        112.0      9.4    955.0   
2         2.2        1402.0                         88.0      9.0    939.0   
3         2.2        1376.0                         80.0      9.2    948.0   
4         1.6        1272.0                         51.0      6.5    836.0   
...       ...           ...                          ...      ...      ...   
1208      4.4        1449.0                        501.0     19.5   1282.0   
1209      3.1        1363.0                        234.0     15.1   1152.0   
1210      3.0        1371.0                        212.0     14.6   1136.0   
1211      3.1        1406.0                        275.0     13.7   1107.0   
1212      3.5        1425.0                        275.0     15.2   1155.0   

      ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0               166.0              1056.0            113.0   
1               103.0              1174.0             92.0   
2               131.0              1140.0            114.0   
3               172.0              1092.0            122.0   
4               131.0              1205.0            116.0   
...               ...                 ...              ...   
1208            254.0               625.0            133.0   
1209            189.0               684.0            110.0   
1210            174.0               689.0            102.0   
1211            167.0               718.0            108.0   
1212            185.0               709.0            110.0   

      OxidoTungstênioNO2  OxidoÍndioO3  Classe  
0                 1692.0        1268.0       0  
1                 1559.0         972.0       0  
2                 1555.0        1074.0       0  
3                 1584.0        1203.0       0  
4                 1490.0        1110.0       0  
...                  ...           ...     ...  
1208              2100.0        1569.0       0  
1209              1951.0        1495.0       0  
1210              1927.0        1471.0       0  
1211              1872.0        1384.0       0  
1212              1936.0        1789.0       0  

[898 rows x 11 columns]

In [ ]:
df_3HidrocarbonetosNãoMetanicos['HidrocarbonetosNãoMetanicos'].median()

150.5

In [ ]:
df_3['HidrocarbonetosNãoMetanicos']= df_3['HidrocarbonetosNãoMetanicos'].replace([-200],150.5)
df_3['HidrocarbonetosNãoMetanicos'].value_counts()

150.5     8437
66.0        14
40.0         9
88.0         8
93.0         8
          ... 
599.0        1
1084.0       1
776.0        1
247.0        1
434.0        1
Name: HidrocarbonetosNãoMetanicos, Length: 428, dtype: int64

In [ ]:
df_3Benzeno=df_3[df_3['Benzeno']>-200.0]
df_3Benzeno

Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0         2.6        1360.0                        150.0     11.9   1046.0   
1         2.0        1292.0                        112.0      9.4    955.0   
2         2.2        1402.0                         88.0      9.0    939.0   
3         2.2        1376.0                         80.0      9.2    948.0   
4         1.6        1272.0                         51.0      6.5    836.0   
...       ...           ...                          ...      ...      ...   
9330      3.1        1314.0                        150.5     13.5   1101.0   
9331      2.4        1163.0                        150.5     11.4   1027.0   
9332      2.4        1142.0                        150.5     12.4   1063.0   
9333      2.1        1003.0                        150.5      9.5    961.0   
9334      2.2        1071.0                        150.5     11.9   1047.0   

      ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0               166.0              1056.0            113.0   
1               103.0              1174.0             92.0   
2               131.0              1140.0            114.0   
3               172.0              1092.0            122.0   
4               131.0              1205.0            116.0   
...               ...                 ...              ...   
9330            472.0               539.0            190.0   
9331            353.0               604.0            179.0   
9332            293.0               603.0            175.0   
9333            235.0               702.0            156.0   
9334            265.0               654.0            168.0   

      OxidoTungstênioNO2  OxidoÍndioO3  Classe  
0                 1692.0        1268.0       0  
1                 1559.0         972.0       0  
2                 1555.0        1074.0       0  
3                 1584.0        1203.0       0  
4                 1490.0        1110.0       0  
...                  ...           ...     ...  
9330              1374.0        1729.0       0  
9331              1264.0        1269.0       0  
9332              1241.0        1092.0       0  
9333              1041.0         770.0       1  
9334              1129.0         816.0       1  

[8969 rows x 11 columns]

In [ ]:
df_3Benzeno['Benzeno'].median()

8.2

In [ ]:
df_3['Benzeno']= df_3['Benzeno'].replace([-200],8.2)
df_3['Benzeno'].value_counts()

8.2     416
3.6      84
2.8      82
3.8      79
4.0      78
       ... 
43.7      1
39.2      1
38.8      1
36.5      1
35.5      1
Name: Benzeno, Length: 407, dtype: int64

In [ ]:
df_3Titania=df_3[df_3['Titania']>-200.0]
df_3Titania['Titania'].median()

909.0

In [ ]:
df_3['Titania']= df_3['Titania'].replace([-200],909.0)
df_3['Titania'].value_counts()

909.0     377
853.0      25
800.0      23
880.0      23
859.0      23
         ... 
1506.0      1
1846.0      1
1770.0      1
481.0       1
1461.0      1
Name: Titania, Length: 1245, dtype: int64

In [ ]:
df_3ConcentraçãoNOx=df_3[df_3['ConcentraçãoNOx']>-200.0]
df_3ConcentraçãoNOx['ConcentraçãoNOx'].median()

180.0

In [ ]:
df_3['ConcentraçãoNOx']= df_3['ConcentraçãoNOx'].replace([-200],180.0)
df_3['ConcentraçãoNOx'].value_counts()

180.0     1672
89.0        41
122.0       36
93.0        36
41.0        36
          ... 
423.0        1
694.0        1
968.0        1
1479.0       1
594.0        1
Name: ConcentraçãoNOx, Length: 925, dtype: int64

In [ ]:
df_3OxidoTungstênioNOx=df_3[df_3['OxidoTungstênioNOx']>-200.0]
df_3OxidoTungstênioNOx['OxidoTungstênioNOx'].median()

805.0

In [ ]:
df_3['OxidoTungstênioNOx']= df_3['OxidoTungstênioNOx'].replace([-200],805.0)
df_3['OxidoTungstênioNOx'].value_counts()

805.0     378
846.0      25
733.0      25
767.0      25
876.0      23
         ... 
1795.0      1
1941.0      1
1917.0      1
1703.0      1
413.0       1
Name: OxidoTungstênioNOx, Length: 1219, dtype: int64

In [ ]:
df_3ConcentraçãoNO2=df_3[df_3['ConcentraçãoNO2']>-200.0]
df_3ConcentraçãoNO2['ConcentraçãoNO2'].median()

109.0

In [ ]:
df_3['ConcentraçãoNO2']= df_3['ConcentraçãoNO2'].replace([-200],109.0)
df_3['ConcentraçãoNO2'].value_counts()

109.0    1704
97.0       78
117.0      77
119.0      76
101.0      75
         ... 
261.0       1
256.0       1
278.0       1
237.0       1
295.0       1
Name: ConcentraçãoNO2, Length: 283, dtype: int64

In [ ]:
df_3OxidoTungstênioNO2=df_3[df_3['OxidoTungstênioNO2']>-200.0]
df_3OxidoTungstênioNO2['OxidoTungstênioNO2'].median()

1463.0

In [ ]:
df_3['OxidoTungstênioNO2']= df_3['OxidoTungstênioNO2'].replace([-200],1463.0)
df_3['OxidoTungstênioNO2'].value_counts()

1463.0    382
1488.0     24
1580.0     22
1539.0     21
1467.0     20
         ... 
2563.0      1
2417.0      1
2603.0      1
2609.0      1
856.0       1
Name: OxidoTungstênioNO2, Length: 1603, dtype: int64

In [ ]:
df_3OxidoÍndioO3=df_3[df_3['OxidoÍndioO3']>-200.0]
df_3OxidoÍndioO3['OxidoÍndioO3'].median()

963.0

In [ ]:
df_3['OxidoÍndioO3']= df_3['OxidoÍndioO3'].replace([-200],963.0)
df_3['OxidoÍndioO3'].value_counts()

963.0     374
836.0      20
825.0      20
826.0      19
926.0      18
         ... 
2165.0      1
2204.0      1
2013.0      1
1912.0      1
374.0       1
Name: OxidoÍndioO3, Length: 1742, dtype: int64

In [ ]:
df_3

Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0         2.6        1360.0                        150.0     11.9   1046.0   
1         2.0        1292.0                        112.0      9.4    955.0   
2         2.2        1402.0                         88.0      9.0    939.0   
3         2.2        1376.0                         80.0      9.2    948.0   
4         1.6        1272.0                         51.0      6.5    836.0   
...       ...           ...                          ...      ...      ...   
9330      3.1        1314.0                        150.5     13.5   1101.0   
9331      2.4        1163.0                        150.5     11.4   1027.0   
9332      2.4        1142.0                        150.5     12.4   1063.0   
9333      2.1        1003.0                        150.5      9.5    961.0   
9334      2.2        1071.0                        150.5     11.9   1047.0   

      ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0               166.0              1056.0            113.0   
1               103.0              1174.0             92.0   
2               131.0              1140.0            114.0   
3               172.0              1092.0            122.0   
4               131.0              1205.0            116.0   
...               ...                 ...              ...   
9330            472.0               539.0            190.0   
9331            353.0               604.0            179.0   
9332            293.0               603.0            175.0   
9333            235.0               702.0            156.0   
9334            265.0               654.0            168.0   

      OxidoTungstênioNO2  OxidoÍndioO3  Classe  
0                 1692.0        1268.0       0  
1                 1559.0         972.0       0  
2                 1555.0        1074.0       0  
3                 1584.0        1203.0       0  
4                 1490.0        1110.0       0  
...                  ...           ...     ...  
9330              1374.0        1729.0       0  
9331              1264.0        1269.0       0  
9332              1241.0        1092.0       0  
9333              1041.0         770.0       1  
9334              1129.0         816.0       1  

[9335 rows x 11 columns]

# Testando

In [ ]:
df_3.shape

(9335, 11)

In [ ]:
feature_columns = ['Cobalto', 'OxidoEstanho','HidrocarbonetosNãoMetanicos','Benzeno','Titania','ConcentraçãoNOx','OxidoTungstênioNOx','ConcentraçãoNO2','OxidoTungstênioNO2','OxidoÍndioO3']
x = df_3[feature_columns].values
y = df_3['Classe'].values
y

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=2)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7468, 10)
(1867, 10)
(7468,)
(1867,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier (n_neighbors=3)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)*100
print ('Acuracia: ', str(round(accuracy,2))+ "%")

Acuracia:  97.91%


In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[856,  22],
       [ 17, 972]], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score 
print (pd.crosstab(y_test,y_pred, rownames=['Real'], colnames=['Predito'], margins=True))

Predito    0    1   All
Real                   
0        856   22   878
1         17  972   989
All      873  994  1867


In [ ]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred)
print("Precision: " + str(round(precision,2)))

Precision: 0.98


In [ ]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred)
print("Recall: " + str(round(recall,2)))


Recall: 0.98


In [ ]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)
print("f1: " + str(round(f1,2)))

f1: 0.98


# Novo Tratamento 

In [ ]:
df_4 = df

In [ ]:
df_4.shape

(9335, 16)

In [ ]:
df_4 = df.drop(columns=['Data','Hora'])
df_4.head()

Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0      2.6          1360                        150.0     11.9   1046.0   
1      2.0          1292                        112.0      9.4    955.0   
2      2.2          1402                         88.0      9.0    939.0   
3      2.2          1376                         80.0      9.2    948.0   
4      1.6          1272                         51.0      6.5    836.0   

   ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  OxidoTungstênioNO2  \
0            166.0              1056.0            113.0              1692.0   
1            103.0              1174.0             92.0              1559.0   
2            131.0              1140.0            114.0              1555.0   
3            172.0              1092.0            122.0              1584.0   
4            131.0              1205.0            116.0              1490.0   

   OxidoÍndioO3  Temperatura-C°  UmidadeRelativa (%)  UmidadeAbsoluta  Classe  
0        1268.0            13.6                 48.9           0.7578       0  
1         972.0            13.3                 47.7           0.7255       0  
2        1074.0            11.9                 54.0           0.7502       0  
3        1203.0            11.0                 60.0           0.7867       0  
4        1110.0            11.2                 59.6           0.7888       0

# Testando

In [ ]:
df_4.shape

(9335, 14)

In [ ]:
feature_columns = ['Cobalto', 'OxidoEstanho','HidrocarbonetosNãoMetanicos','Benzeno','Titania','ConcentraçãoNOx','OxidoTungstênioNOx','ConcentraçãoNO2','OxidoTungstênioNO2','OxidoÍndioO3','Temperatura-C°','UmidadeRelativa (%)','UmidadeAbsoluta']
x = df_4[feature_columns].values
y = df_4['Classe'].values
y

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=2)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7468, 13)
(1867, 13)
(7468,)
(1867,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier (n_neighbors=3)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)*100
print ('Acuracia: ', str(round(accuracy,2))+ "%")

Acuracia:  98.13%


In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[857,  21],
       [ 14, 975]], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score 
print (pd.crosstab(y_test,y_pred, rownames=['Real'], colnames=['Predito'], margins=True))

Predito    0    1   All
Real                   
0        857   21   878
1         14  975   989
All      871  996  1867


In [ ]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred)
print("Precision: " + str(round(precision,2)))

Precision: 0.98


In [ ]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred)
print("Recall: " + str(round(recall,2)))


Recall: 0.99


In [ ]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)
print("f1: " + str(round(f1,2)))

f1: 0.98


# Novo Tratamento

In [ ]:
df_5 = df
df_5

Data      Hora  Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  \
0     10/03/04  18:00:00      2.6          1360                        150.0   
1     10/03/04  19:00:00      2.0          1292                        112.0   
2     10/03/04  20:00:00      2.2          1402                         88.0   
3     10/03/04  21:00:00      2.2          1376                         80.0   
4     10/03/04  22:00:00      1.6          1272                         51.0   
...        ...       ...      ...           ...                          ...   
9330  04/04/05  10:00:00      3.1          1314                       -200.0   
9331  04/04/05  11:00:00      2.4          1163                       -200.0   
9332  04/04/05  12:00:00      2.4          1142                       -200.0   
9333  04/04/05  13:00:00      2.1          1003                       -200.0   
9334  04/04/05  14:00:00      2.2          1071                       -200.0   

      Benzeno  Titania  ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0        11.9   1046.0            166.0              1056.0            113.0   
1         9.4    955.0            103.0              1174.0             92.0   
2         9.0    939.0            131.0              1140.0            114.0   
3         9.2    948.0            172.0              1092.0            122.0   
4         6.5    836.0            131.0              1205.0            116.0   
...       ...      ...              ...                 ...              ...   
9330     13.5   1101.0            472.0               539.0            190.0   
9331     11.4   1027.0            353.0               604.0            179.0   
9332     12.4   1063.0            293.0               603.0            175.0   
9333      9.5    961.0            235.0               702.0            156.0   
9334     11.9   1047.0            265.0               654.0            168.0   

      OxidoTungstênioNO2  OxidoÍndioO3  Temperatura-C°  UmidadeRelativa (%)  \
0                 1692.0        1268.0            13.6                 48.9   
1                 1559.0         972.0            13.3                 47.7   
2                 1555.0        1074.0            11.9                 54.0   
3                 1584.0        1203.0            11.0                 60.0   
4                 1490.0        1110.0            11.2                 59.6   
...                  ...           ...             ...                  ...   
9330              1374.0        1729.0            21.9                 29.3   
9331              1264.0        1269.0            24.3                 23.7   
9332              1241.0        1092.0            26.9                 18.3   
9333              1041.0         770.0            28.3                 13.5   
9334              1129.0         816.0            28.5                 13.1   

      UmidadeAbsoluta  Classe  
0              0.7578       0  
1              0.7255       0  
2              0.7502       0  
3              0.7867       0  
4              0.7888       0  
...               ...     ...  
9330           0.7568       0  
9331           0.7119       0  
9332           0.6406       0  
9333           0.5139       1  
9334           0.5028       1  

[9335 rows x 16 columns]

In [ ]:
df_5 = df.drop(columns=['Data','Hora','Temperatura-C°','UmidadeRelativa (%)','UmidadeAbsoluta'])
df_5.head()

Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0      2.6          1360                        150.0     11.9   1046.0   
1      2.0          1292                        112.0      9.4    955.0   
2      2.2          1402                         88.0      9.0    939.0   
3      2.2          1376                         80.0      9.2    948.0   
4      1.6          1272                         51.0      6.5    836.0   

   ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  OxidoTungstênioNO2  \
0            166.0              1056.0            113.0              1692.0   
1            103.0              1174.0             92.0              1559.0   
2            131.0              1140.0            114.0              1555.0   
3            172.0              1092.0            122.0              1584.0   
4            131.0              1205.0            116.0              1490.0   

   OxidoÍndioO3  Classe  
0        1268.0       0  
1         972.0       0  
2        1074.0       0  
3        1203.0       0  
4        1110.0       0

In [ ]:
df_5.replace([-200], 0, inplace=True)

### Normalização

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

nomes_cols = ['Cobalto', 'OxidoEstanho','HidrocarbonetosNãoMetanicos','Benzeno','Titania','ConcentraçãoNOx','OxidoTungstênioNOx','ConcentraçãoNO2','OxidoTungstênioNO2','OxidoÍndioO3','Classe']

print(scaler.fit(df_5))

df_5 = scaler.transform(df_5)
df_5 = pd.DataFrame(df_5, columns= nomes_cols).round(2)
df_5

MinMaxScaler()


Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0        0.22          0.67                         0.13     0.19     0.47   
1        0.17          0.63                         0.09     0.15     0.43   
2        0.18          0.69                         0.07     0.14     0.42   
3        0.18          0.67                         0.07     0.14     0.43   
4        0.13          0.62                         0.04     0.10     0.38   
...       ...           ...                          ...      ...      ...   
9330     0.26          0.64                         0.00     0.21     0.50   
9331     0.20          0.57                         0.00     0.18     0.46   
9332     0.20          0.56                         0.00     0.19     0.48   
9333     0.18          0.49                         0.00     0.15     0.43   
9334     0.18          0.52                         0.00     0.19     0.47   

      ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0                0.11                0.39             0.33   
1                0.07                0.44             0.27   
2                0.09                0.42             0.34   
3                0.12                0.41             0.36   
4                0.09                0.45             0.34   
...               ...                 ...              ...   
9330             0.32                0.20             0.56   
9331             0.24                0.23             0.53   
9332             0.20                0.22             0.51   
9333             0.16                0.26             0.46   
9334             0.18                0.24             0.49   

      OxidoTungstênioNO2  OxidoÍndioO3  Classe  
0                   0.61          0.50     0.0  
1                   0.56          0.39     0.0  
2                   0.56          0.43     0.0  
3                   0.57          0.48     0.0  
4                   0.54          0.44     0.0  
...                  ...           ...     ...  
9330                0.50          0.69     0.0  
9331                0.46          0.50     0.0  
9332                0.45          0.43     0.0  
9333                0.38          0.31     1.0  
9334                0.41          0.32     1.0  

[9335 rows x 11 columns]

# Testando

In [ ]:
df_5.shape

(9335, 11)

In [ ]:
feature_columns = ['Cobalto', 'OxidoEstanho','HidrocarbonetosNãoMetanicos','Benzeno','Titania','ConcentraçãoNOx','OxidoTungstênioNOx','ConcentraçãoNO2','OxidoTungstênioNO2','OxidoÍndioO3']
x = df_5[feature_columns].values
y = df_5['Classe'].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=2)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier (n_neighbors=3)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
y_pred

(7468, 10)
(1867, 10)
(7468,)
(1867,)


array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)*100
print ('Acuracia: ', str(round(accuracy,2))+ "%")

Acuracia:  97.43%


In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[845,  33],
       [ 15, 974]], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score 
print (pd.crosstab(y_test,y_pred, rownames=['Real'], colnames=['Predito'], margins=True))

Predito    0     1   All
Real                    
0        845    33   878
1         15   974   989
All      860  1007  1867


In [ ]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred)
print("Precision: " + str(round(precision,2)))

Precision: 0.97


In [ ]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred)
print("Recall: " + str(round(recall,2)))

Recall: 0.98


In [ ]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)
print("f1: " + str(round(f1,2)))

f1: 0.98


# Novo Tratamento

In [ ]:
df_6 = df
df_6

Data      Hora  Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  \
0     10/03/04  18:00:00      2.6          1360                        150.0   
1     10/03/04  19:00:00      2.0          1292                        112.0   
2     10/03/04  20:00:00      2.2          1402                         88.0   
3     10/03/04  21:00:00      2.2          1376                         80.0   
4     10/03/04  22:00:00      1.6          1272                         51.0   
...        ...       ...      ...           ...                          ...   
9330  04/04/05  10:00:00      3.1          1314                       -200.0   
9331  04/04/05  11:00:00      2.4          1163                       -200.0   
9332  04/04/05  12:00:00      2.4          1142                       -200.0   
9333  04/04/05  13:00:00      2.1          1003                       -200.0   
9334  04/04/05  14:00:00      2.2          1071                       -200.0   

      Benzeno  Titania  ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0        11.9   1046.0            166.0              1056.0            113.0   
1         9.4    955.0            103.0              1174.0             92.0   
2         9.0    939.0            131.0              1140.0            114.0   
3         9.2    948.0            172.0              1092.0            122.0   
4         6.5    836.0            131.0              1205.0            116.0   
...       ...      ...              ...                 ...              ...   
9330     13.5   1101.0            472.0               539.0            190.0   
9331     11.4   1027.0            353.0               604.0            179.0   
9332     12.4   1063.0            293.0               603.0            175.0   
9333      9.5    961.0            235.0               702.0            156.0   
9334     11.9   1047.0            265.0               654.0            168.0   

      OxidoTungstênioNO2  OxidoÍndioO3  Temperatura-C°  UmidadeRelativa (%)  \
0                 1692.0        1268.0            13.6                 48.9   
1                 1559.0         972.0            13.3                 47.7   
2                 1555.0        1074.0            11.9                 54.0   
3                 1584.0        1203.0            11.0                 60.0   
4                 1490.0        1110.0            11.2                 59.6   
...                  ...           ...             ...                  ...   
9330              1374.0        1729.0            21.9                 29.3   
9331              1264.0        1269.0            24.3                 23.7   
9332              1241.0        1092.0            26.9                 18.3   
9333              1041.0         770.0            28.3                 13.5   
9334              1129.0         816.0            28.5                 13.1   

      UmidadeAbsoluta  Classe  
0              0.7578       0  
1              0.7255       0  
2              0.7502       0  
3              0.7867       0  
4              0.7888       0  
...               ...     ...  
9330           0.7568       0  
9331           0.7119       0  
9332           0.6406       0  
9333           0.5139       1  
9334           0.5028       1  

[9335 rows x 16 columns]

In [ ]:
df_6 = df.drop(columns=['Data','Hora','Temperatura-C°','UmidadeRelativa (%)','UmidadeAbsoluta'])
df_6.head()


Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0      2.6          1360                        150.0     11.9   1046.0   
1      2.0          1292                        112.0      9.4    955.0   
2      2.2          1402                         88.0      9.0    939.0   
3      2.2          1376                         80.0      9.2    948.0   
4      1.6          1272                         51.0      6.5    836.0   

   ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  OxidoTungstênioNO2  \
0            166.0              1056.0            113.0              1692.0   
1            103.0              1174.0             92.0              1559.0   
2            131.0              1140.0            114.0              1555.0   
3            172.0              1092.0            122.0              1584.0   
4            131.0              1205.0            116.0              1490.0   

   OxidoÍndioO3  Classe  
0        1268.0       0  
1         972.0       0  
2        1074.0       0  
3        1203.0       0  
4        1110.0       0

In [ ]:
df_6.replace([-200], 0, inplace=True)

### Padronização

In [ ]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
nomes_cols = ['Cobalto', 'OxidoEstanho','HidrocarbonetosNãoMetanicos','Benzeno','Titania','ConcentraçãoNOx','OxidoTungstênioNOx','ConcentraçãoNO2','OxidoTungstênioNO2','OxidoÍndioO3','Classe']

df_6 = scaler.fit_transform(df_6)
df_6 = pd.DataFrame(df_6, columns=nomes_cols).round(2)
df_6  


Cobalto  OxidoEstanho  HidrocarbonetosNãoMetanicos  Benzeno  Titania  \
0        0.54          1.01                         1.42     0.29     0.45   
1        0.15          0.78                         1.00    -0.04     0.17   
2        0.28          1.15                         0.73    -0.09     0.11   
3        0.28          1.06                         0.65    -0.06     0.14   
4       -0.11          0.72                         0.33    -0.42    -0.21   
...       ...           ...                          ...      ...      ...   
9330     0.86          0.86                        -0.23     0.50     0.62   
9331     0.41          0.35                        -0.23     0.23     0.39   
9332     0.41          0.28                        -0.23     0.36     0.50   
9333     0.22         -0.18                        -0.23    -0.02     0.18   
9334     0.28          0.05                        -0.23     0.29     0.45   

      ConcentraçãoNOx  OxidoTungstênioNOx  ConcentraçãoNO2  \
0               -0.18                0.85             0.32   
1               -0.47                1.24            -0.02   
2               -0.34                1.13             0.34   
3               -0.15                0.97             0.47   
4               -0.34                1.35             0.37   
...               ...                 ...              ...   
9330             1.25               -0.88             1.57   
9331             0.69               -0.66             1.39   
9332             0.41               -0.67             1.33   
9333             0.15               -0.34             1.02   
9334             0.28               -0.50             1.22   

      OxidoTungstênioNO2  OxidoÍndioO3  Classe  
0                   0.66          0.65   -1.10  
1                   0.36         -0.02   -1.10  
2                   0.35          0.21   -1.10  
3                   0.42          0.50   -1.10  
4                   0.21          0.29   -1.10  
...                  ...           ...     ...  
9330               -0.06          1.70   -1.10  
9331               -0.31          0.65   -1.10  
9332               -0.36          0.25   -1.10  
9333               -0.81         -0.49    0.91  
9334               -0.61         -0.38    0.91  

[9335 rows x 11 columns]

# Testando

In [ ]:
df_6.shape

(9335, 11)

In [ ]:
feature_columns = ['Cobalto', 'OxidoEstanho','HidrocarbonetosNãoMetanicos','Benzeno','Titania','ConcentraçãoNOx','OxidoTungstênioNOx','ConcentraçãoNO2','OxidoTungstênioNO2','OxidoÍndioO3']
x = df_6[feature_columns].values
y = df_6['Classe'].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=2)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier (n_neighbors=3)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
y_pred

(7468, 10)
(1867, 10)
(7468,)
(1867,)


array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)*100
print ('Acuracia: ', str(round(accuracy,2))+ "%")

Acuracia:  97.48%


In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[845,  33],
       [ 14, 975]], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score 
print (pd.crosstab(y_test,y_pred, rownames=['Real'], colnames=['Predito'], margins=True))

Predito    0     1   All
Real                    
0        845    33   878
1         14   975   989
All      859  1008  1867


In [ ]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred)
print("Precision: " + str(round(precision,2)))

Precision: 0.97


In [ ]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred)
print("Recall: " + str(round(recall,2)))

Recall: 0.99


In [ ]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)
print("f1: " + str(round(f1,2)))

f1: 0.98
